Og map
swarm-wustl/just-keep-swarming pull request #4
Opened 2024-10-04 23:55 UTC by jaximus808

Implemented map maker node that stores a OG grid. Modified camera data to have input camera data params (like cam height). I added services and pub and subs to have map maker respond when given map data and update accordingly.

Eugene will work on make the function to transform pixel to real points.

2024-10-11 23:37 UTC, jaximus808 commented
I'm going to add tests in the next commit, also need to handle merge conflicts.

2024-10-12 21:06 UTC, jaximus808 commented
Added tests, handling merge conflcits

2024-10-12 21:13 UTC, jaximus808 commented
merge conflicts done, review pls

2024-10-17 01:03 UTC, sebtheiler requested changes
See notes. Very good overall just a few minor things

2024-10-17 01:03 UTC, sebtheiler commented on ros/.vscode/settings.json
> +{
Don't commit vscode settings. This is also specific to you because it has your username in it

2024-10-17 01:03 UTC, sebtheiler commented on ros/src/camera_feed/camera_feed/camera_feed.py
> +class CamData:
Splitting the logic of nodes into functions is good, but I don't think it makes sense to have a separate class that just declares and gets parameters. Parameters are meant to be attached to the node class so having a different class that does it for that class is a little convoluted.

What I mean by having thin nodes and extracting logic is to actually extract the _logic_ part of nodes into individual functions. Setting up parameters isn't really logic. There's no reason to extract it because it would never be used in a different class/function

2024-10-17 01:03 UTC, sebtheiler commented on ros/src/camera_feed/camera_feed/camera_feed.py
> +    def get_meta_data(self, request, response):
I would have this as a separate function, not as part of a class. Also probably in a utils or common file

2024-10-17 01:03 UTC, sebtheiler commented on ros/src/camera_feed/camera_feed/camera_feed.py
> +        match request.units:
Why match over if?

2024-10-17 01:03 UTC, sebtheiler commented on ros/src/map_maker/LICENSE
> +                        http://www.apache.org/licenses/
Don't think we need a license in every package?

2024-10-17 01:03 UTC, sebtheiler commented on ros/src/map_maker/map_maker/map_maker.py
> +def calculate_pos(points):
I like that this is functional. This is good; how most things should be written. Only change might be to put the functions in a separate file from the node

2024-10-17 01:03 UTC, sebtheiler commented on ros/src/map_maker/package.xml
> +  <description>TODO: Package description</description>
nit: add description

2024-10-17 01:03 UTC, sebtheiler commented on ros/src/map_maker/test/test_map.py
> +                [
Use `[0]*n` instead of manually typing a bunch of zeroes. Then update one index to 1. It'll be way easier to read

2024-10-17 01:03 UTC, sebtheiler commented on ros/src/map_maker/test/test_map.py
> +                "b", [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
Same for this and the one below

2024-10-17 01:03 UTC, sebtheiler commented on ros/src/map_maker/map_maker/map_maker.py
> +    def set_map(self, data):
Should data maybe be replaced by `width, height`? That seems to be all that's used here

2024-10-17 01:03 UTC, sebtheiler commented on ros/src/map_maker/map_maker/map_maker.py
> +        self.cam_data = [self.cam_data["focal_length"], self.cam_data["cam_height"]]
Why lines 109-111 when you have this right after?

2024-10-18 21:21 UTC, jaximus808 commented on ros/src/camera_feed/camera_feed/camera_feed.py
> +class CamData:
The reason why I did this is to reduce the amount of instance variables used for the cam set up which we kinda need.

Pylint was throwing a fit cuz of it and I couldn't really find a way around it without creating a separate class that stores the settings

2024-10-18 21:23 UTC, jaximus808 commented on ros/src/camera_feed/camera_feed/camera_feed.py
> +        match request.units:
The idea is that there would alot of units this method could accept. I personally may remove this and we can just agree to just use meters. Let me know what you think

2024-10-18 21:23 UTC, jaximus808 commented on ros/src/map_maker/LICENSE
> +                        http://www.apache.org/licenses/
oops

2024-10-18 21:24 UTC, jaximus808 commented on ros/src/map_maker/package.xml
> +  <description>TODO: Package description</description>
got it

2024-10-18 21:25 UTC, jaximus808 commented on ros/src/map_maker/test/test_map.py
> +                [
lowkey i just used chat to do these tests. Before it was written to where it created a by square shape, but pylint kinda changed it.

I can prob change it tho

2024-10-18 21:37 UTC, jaximus808 commented on ros/src/map_maker/map_maker/map_maker.py
> +        self.cam_data = [self.cam_data["focal_length"], self.cam_data["cam_height"]]
oops my bad

fixed

2025-02-13 01:42 UTC, sebtheiler submitted a review, later dismissed

2025-02-13 01:44 UTC, sebtheiler approved these changes

2025-02-13 01:44 UTC, merged